# Generated by Django 5.1 on 2024-11-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Hotel', '0005_payment_card_number_payment_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='security_code',
            new_name='ccv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='expire_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expire_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
