# Generated by Django 5.1 on 2024-11-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Hotel', '0006_rename_security_code_payment_ccv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ManyToManyField(related_name='payment', to='App_Hotel.booking'),
        ),
    ]
