# Generated by Django 5.1 on 2024-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Hotel', '0007_remove_payment_booking_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
