# Generated by Django 5.1 on 2024-11-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_alter_user_is_staff'),
        ('App_Hotel', '0008_payment_is_cancelled_payment_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='App_Hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='App_Auth.customerprofile')),
            ],
            options={
                'unique_together': {('user', 'hotel')},
            },
        ),
    ]
