# Generated by Django 5.1 on 2024-11-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_alter_user_is_staff'),
        ('App_Hotel', '0010_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='App_Auth.customerprofile'),
        ),
    ]
