# Generated by Django 5.1 on 2024-11-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_alter_user_is_staff'),
        ('App_Hotel', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to='App_Auth.customerprofile'),
        ),
    ]
